/**
 * @fileoverview gRPC-Web generated client stub for file
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: file.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as file_pb from './file_pb'; // proto import: "file.proto"


export class FileServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetAllFiles = new grpcWeb.MethodDescriptor(
    '/file.FileService/GetAllFiles',
    grpcWeb.MethodType.UNARY,
    file_pb.GetFileByUser,
    file_pb.FileList,
    (request: file_pb.GetFileByUser) => {
      return request.serializeBinary();
    },
    file_pb.FileList.deserializeBinary
  );

  getAllFiles(
    request: file_pb.GetFileByUser,
    metadata?: grpcWeb.Metadata | null): Promise<file_pb.FileList>;

  getAllFiles(
    request: file_pb.GetFileByUser,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: file_pb.FileList) => void): grpcWeb.ClientReadableStream<file_pb.FileList>;

  getAllFiles(
    request: file_pb.GetFileByUser,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: file_pb.FileList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/file.FileService/GetAllFiles',
        request,
        metadata || {},
        this.methodDescriptorGetAllFiles,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/file.FileService/GetAllFiles',
    request,
    metadata || {},
    this.methodDescriptorGetAllFiles);
  }

  methodDescriptorUploadFile = new grpcWeb.MethodDescriptor(
    '/file.FileService/UploadFile',
    grpcWeb.MethodType.UNARY,
    file_pb.UploadFileRequest,
    file_pb.UploadFileResponse,
    (request: file_pb.UploadFileRequest) => {
      return request.serializeBinary();
    },
    file_pb.UploadFileResponse.deserializeBinary
  );

  uploadFile(
    request: file_pb.UploadFileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<file_pb.UploadFileResponse>;

  uploadFile(
    request: file_pb.UploadFileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: file_pb.UploadFileResponse) => void): grpcWeb.ClientReadableStream<file_pb.UploadFileResponse>;

  uploadFile(
    request: file_pb.UploadFileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: file_pb.UploadFileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/file.FileService/UploadFile',
        request,
        metadata || {},
        this.methodDescriptorUploadFile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/file.FileService/UploadFile',
    request,
    metadata || {},
    this.methodDescriptorUploadFile);
  }

}

